name: Semantic Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run semantic release script
        id: semrel
        run: bash ./semantic-release.sh

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semrel.outputs.version }}
          release_name: Release ${{ steps.semrel.outputs.version }}
          draft: false
          prerelease: false

